/* This file is expected to be #included with various #definitions of _OBJ_VM_MKSYM */

_OBJ_VM_MKSYM(module)
_OBJ_VM_MKSYM(from)
_OBJ_VM_MKSYM(def)
_OBJ_VM_MKSYM(in)
_OBJ_VM_MKSYM(out)
_OBJ_VM_MKSYM(docs)
_OBJ_VM_MKSYM(arrow)

_OBJ_VM_MKSYM(dup)
_OBJ_VM_MKSYM(drop)
_OBJ_VM_MKSYM(swap)
_OBJ_VM_MKSYM(nip)
_OBJ_VM_MKSYM(tuck)
_OBJ_VM_MKSYM(over)

_OBJ_VM_MKSYM(p)
_OBJ_VM_MKSYM(p_stack)
_OBJ_VM_MKSYM(p_vars)
_OBJ_VM_MKSYM(p_blocks)
_OBJ_VM_MKSYM(p_frame)

_OBJ_VM_MKSYM(str_p)
